mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: dev.itboot.mb.model
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    initialization-mode: always
    url: jdbc:mysql://確認したエンドポイント/ebdb
    username: admin
    password: 設定したパスワード
